### ISSUE TITLE
why use [state, time] as the input to value function?

### ISSUE THREAD

**Issue by jiangsy** [ajlangley/trpo-pytorch#4]

**Comment by ajlangley** [comment]
Sorry, I am just seeing this now. In short, it helps the value function to learn more easily, since every episode is of a fixed length, so states can be more or less advantageous depending on the time at which the agent is in them. For instance, if T=50 and we are making a value prediction at t=49, the value function should give low predictions regardless of the state, because there is only 1 tilmestep left for the agent collect rewards.

Let me know if that's not clear enough.

**Comment by jiangsy** [comment]
sorry for a late reply. really appreciate such a detailed explanation. so this extra info shouldn't cause a big difference in the performance right?

**Comment by ajlangley** [comment]
It does, in fact, cause a big difference in performance. Adding time as an input makes the value function much easier to learn and leads to far better performance, which improved the performance of the learned policy because the approximation to the policy gradient becomes more accurate.

Personally, my own experience indicated that the value function really didn't learn well at all without adding time.

**Comment by jiangsy** [comment]
thanks for your insight, i would try add times back in the training
